# Generated by Django 5.2.3 on 2025-06-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cargo_code', models.CharField(max_length=50, unique=True)),
                ('weight_kg', models.FloatField()),
                ('volume_m3', models.FloatField()),
                ('packages_count', models.IntegerField(default=1)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('requires_cold_storage', models.BooleanField(default=False)),
                ('fragile', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('standard', 'Стандартный'), ('food', 'Пищевой'), ('electronic', 'Электроника'), ('chemical', 'Химия'), ('medical', 'Медицинский'), ('other', 'Другое')], default='standard', max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(choices=[('created', 'Создан'), ('arrived', 'Поступил на склад'), ('stored', 'Размещён'), ('processing', 'Обрабатывается'), ('dispatched', 'Отгружен')], default='created', max_length=30)),
                ('location', models.CharField(blank=True, help_text='Произвольное описание местоположения груза (например, зона A3, полка 5)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Общий пул', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qualifications', models.ManyToManyField(blank=True, to='core.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('employees', models.ManyToManyField(related_name='shifts', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает назначения'), ('in_progress', 'Выполняется'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('urgent', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo')),
                ('required_qualifications', models.ManyToManyField(blank=True, to='core.qualification')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.shift')),
                ('task_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.taskpool')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShiftStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.IntegerField(default=0)),
                ('shift_score', models.IntegerField(default=0)),
                ('is_busy', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_stats', to='core.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_stats', to='core.shift')),
            ],
            options={
                'unique_together': {('employee', 'shift')},
            },
        ),
    ]
