# Generated by Django 5.2.3 on 2025-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
