# Generated by Django 5.2.3 on 2025-10-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationslot',
            name='size_class',
        ),
    ]
