# Generated by Django 5.2.3 on 2025-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='shifts', through='core.EmployeeShiftStats', to='core.employee'),
        ),
    ]
