# Generated by Django 5.2.3 on 2025-09-13 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', '-start_time', 'id']},
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(related_name='shifts', through='core.EmployeeShiftStats', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'is_active'], name='core_shift_date_cda6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['-start_time'], name='core_shift_start_t_43cca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('start_time__isnull', False), _connector='OR'), name='shift_end_requires_start'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='shift_end_after_start'),
        ),
    ]
