# Generated by Django 5.2.3 on 2025-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shift_options_shift_created_at_shift_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeshiftstats',
            options={'ordering': ['-shift_score', 'task_count', 'employee_id']},
        ),
        migrations.AddField(
            model_name='employeeshiftstats',
            name='last_task_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='employeeshiftstats',
            index=models.Index(fields=['shift', 'is_busy'], name='core_employ_shift_i_4a5b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftstats',
            index=models.Index(fields=['employee', 'shift'], name='core_employ_employe_7eb240_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftstats',
            index=models.Index(fields=['-shift_score', 'task_count'], name='core_employ_shift_s_eddeea_idx'),
        ),
    ]
