# Generated by Django 5.2.3 on 2025-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_locationslot_size_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('RECEIVE_TO_INBOUND', 'Receive to inbound'), ('PUTAWAY_TO_RACK', 'Putaway to rack'), ('MOVE_BETWEEN_SLOTS', 'Move between slots'), ('DISPATCH_CARGO', 'Dispatch cargo'), ('GENERAL', 'GENERAL TASK')], db_index=True, max_length=40),
        ),
    ]
