# Generated by Django 5.2.3 on 2025-06-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pool',
        ),
    ]
