# Generated by Django 5.2.3 on 2025-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeshiftstats',
            options={'ordering': ['-shift_score', 'task_completed_count', 'employee_id']},
        ),
        migrations.RemoveIndex(
            model_name='employeeshiftstats',
            name='core_employ_shift_s_eddeea_idx',
        ),
        migrations.RenameField(
            model_name='employeeshiftstats',
            old_name='task_count',
            new_name='task_completed_count',
        ),
        migrations.AddField(
            model_name='employeeshiftstats',
            name='task_assigned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cargoevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taskassignmentlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='employeeshiftstats',
            index=models.Index(fields=['-shift_score', 'task_completed_count'], name='core_employ_shift_s_9aaf3e_idx'),
        ),
    ]
