# Generated by Django 5.2.3 on 2025-09-13 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employeeshiftstats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpool',
            options={'ordering': ['-is_active', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='taskpool',
            name='auto_assign_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskpool',
            name='default_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskpool',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='taskpool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskpool',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
