# Generated by Django 5.2.3 on 2026-04-25 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employeeshiftstats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('RECEIVE_TO_INBOUND', 'Receive to inbound'), ('PUTAWAY_TO_RACK', 'Putaway to rack'), ('MOVE_BETWEEN_SLOTS', 'Move between slots'), ('DISPATCH_CARGO', 'Dispatch cargo'), ('GENERAL', 'GENERAL TASK')], db_index=True, max_length=40, verbose_name='Тип задачи')),
                ('performance_factor', models.FloatField(default=1.0, help_text='Меньше 1.0 – сотрудник обычно быстрее среднего по этому типу задач, больше 1.0 – медленнее.', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Коэффициент производительности')),
                ('sigma', models.FloatField(default=0.1, help_text='Насколько стабильно сотрудник выполняет этот тип задач.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Разброс')),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Сколько выполненных задач лежит в основе профиля.', verbose_name='Число наблюдений')),
                ('mean_minutes', models.FloatField(blank=True, help_text='Служебное поле для аналитики и пересчёта профиля.', null=True, verbose_name='Среднее фактическое время')),
                ('source_kind', models.CharField(choices=[('synthetic', 'Synthetic'), ('real', 'Real'), ('mixed', 'Mixed')], default='synthetic', max_length=16, verbose_name='Источник профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_profiles', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника по типу задач',
                'verbose_name_plural': 'Профили сотрудников по типам задач',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaskQualificationModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0, help_text='Дополнительный множитель, если задача этого типа требует данную квалификацию.', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Поправочный коэффициент')),
                ('sigma_bonus', models.FloatField(default=0.0, help_text='Насколько наличие этой квалификации влияет на вариативность времени.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Добавка к разбросу')),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Сколько наблюдений лежит в основе этой поправки.', verbose_name='Число наблюдений')),
                ('source_kind', models.CharField(choices=[('synthetic', 'Synthetic'), ('real', 'Real'), ('mixed', 'Mixed')], default='synthetic', max_length=16, verbose_name='Источник поправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_modifiers', to='core.employeetaskprofile', verbose_name='Базовый профиль')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_profile_modifiers', to='core.qualification', verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Поправка профиля по квалификации',
                'verbose_name_plural': 'Поправки профилей по квалификациям',
            },
        ),
        migrations.AddIndex(
            model_name='employeetaskprofile',
            index=models.Index(fields=['employee', 'task_type'], name='core_employ_employe_941250_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetaskprofile',
            index=models.Index(fields=['task_type'], name='core_employ_task_ty_d7eaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetaskprofile',
            index=models.Index(fields=['source_kind'], name='core_employ_source__1ead6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeetaskprofile',
            constraint=models.UniqueConstraint(fields=('employee', 'task_type'), name='uniq_employee_task_profile'),
        ),
        migrations.AddIndex(
            model_name='employeetaskqualificationmodifier',
            index=models.Index(fields=['qualification'], name='core_employ_qualifi_91d867_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetaskqualificationmodifier',
            index=models.Index(fields=['source_kind'], name='core_employ_source__18c4d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeetaskqualificationmodifier',
            constraint=models.UniqueConstraint(fields=('profile', 'qualification'), name='uniq_profile_qualification_modifier'),
        ),
    ]
