# Generated by Django 5.2.3 on 2025-11-01 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_type', models.CharField(max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('event_hash', models.CharField(db_index=True, max_length=64)),
                ('in_block', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('prev_block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('merkle_root', models.CharField(max_length=64)),
                ('block_hash', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='BlockMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_index', models.IntegerField()),
                ('leaf_hash', models.CharField(max_length=64)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.block')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='audit.auditevent')),
            ],
            options={
                'ordering': ['leaf_index'],
                'unique_together': {('block', 'leaf_index')},
            },
        ),
    ]
